<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            var guidediv = '#userGuide_fifth-head';
            wweSmCurrentPlanNote($, '<?php echo $this->wweSmallPlanNotice(); ?>', guidediv);
        });
    });
</script>
<div class="user_guide">
    <p>
        <?=
            /* @noEscape */ __(
                "The User Guide for this application is maintained on the publisher's website. To view it click <a href='%1' target='_blank'>here</a> or paste the following link into your browser.",
                "https://eniture.com/magento2-worldwide-express-small-package/#documentation"
            )
                                        ?>
    </p>
    <?= "https://eniture.com/magento2-worldwide-express-small-package/#documentation" ?>
</div>