<?php
$advancedPlan = false;
$class = 'disabledDiv';
$disableInput = 'disabled="disabled"';
if ($block->currentPlan == 3) {
    $advancedPlan = true;
    $class = '';
    $disableInput = '';
}
?>
<script>
    require(['jquery', 'domReady!'], function($){
        let carrierDiv = '#WweSmWarehouse_second-head';
        wweSmCurrentPlanNote($, '<?php echo $block->wweSmallSetPlanNotice(); ?>', carrierDiv);

        let canAddWh = <?php echo $block->canAddWarehouse; ?>;
        wweSmAddWarehouseRestriction(canAddWh);
    });
    let wweSmAjaxUrl = '<?=  $block->getAjaxUrl() ?>';
    let wweSmAdvancePlan = '<?=  $advancedPlan ?>';

</script>
</form>
<div class="main-container">
    <h1>
        <?=
        /* @noEscape */ __('Warehouses')
        ?>
    </h1>
    <a href="#" class="en-btn" id="wwesm-add-wh-btn" title="<?= /* @noEscape */ __('Add Warehouse') ?>">
        <?= /* @noEscape */ __('Add') ?>
    </a>
    <div class="wh-text">
        <p>
            <?=
            /* @noEscape */ __('Warehouses that inventory all products not otherwise identified as drop shipped items. The warehouse with the lowest shipping cost to the destination is used for quoting purposes.')
            ?>
        </p>
    </div>
    <div class="message message-success success wwesm-wh-msg"></div>

    <table class="warehouse" id="append-warehouse">
        <thead>
        <tr>
            <th>
                <?=
                /* @noEscape */ __('City')
                ?>
            </th>
            <th>
                <?=
                /* @noEscape */ __('State')
                ?>
            </th>
            <th>
                <?=
                /* @noEscape */ __('Zip')
                ?>
            </th>
            <th>
                <?=
                /* @noEscape */ __('Country')
                ?>
            </th>
            <th>
                <?=
                /* @noEscape */ __('Action')
                ?>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php
        if ($block->warehouses) {
            foreach ($block->warehouses as $r) {
                ?>
                <tr id="row_<?= /* @noEscape */ $r['warehouse_id']; ?>" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>">
                    <td>
                        <?= /* @noEscape */ $r['city']; ?>
                    </td>
                    <td>
                        <?= /* @noEscape */ $r['state']; ?>
                    </td>
                    <td>
                        <?= /* @noEscape */ $r['zip']; ?>
                    </td>
                    <td>
                        <?= /* @noEscape */ $r['country']; ?>
                    </td>
                    <td>
                  <a href="javascript:;" data-id="<?= $r['warehouse_id']; ?>" title="<?=  __('Edit') ?>" class="wwesm-edit-wh">
                        <?=  __('Edit') ?>
                  </a> |
                  <a href="javascript:;" data-id="<?= $r['warehouse_id']; ?>" title="<?= __('Delete') ?>" class="wwesm-del-wh">
                        <?=  __('Delete') ?>
                        </a>
                    </td>
                </tr>
            <?php   }
        }
        ?>
        </tbody>
    </table>

    <hr class="wh-hr">
</div>
<!-- Add Popup for new warehouse -->
<div id="wwesm-wh-modal" class="add-wh-popup">
<form method="post" id="wwesm-wh-form" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation":{}}' >


                <div class="message message-error error wwesm-wh-er-msg"></div>
                <input type="hidden" name="location" value="warehouse">
                <input type="hidden" name="originId" id="edit-form-id">
                <div class="add-wh-input">
                    <div class="wh-input-label add-asterisk">
                        <?= /* @noEscape */ __('Zip') ?>
                    </div>
                    <div class="wh-input">
                        <input type="text" class="required-entry validate-alphanum" title="<?=  __('Zip') ?>" maxlength="6" name="zip" placeholder="30214" id="wwesm-wh-zip">
                    </div>
                </div>

                <div class="add-wh-input city-input">
                    <div class="wh-input-label add-asterisk">
                        <?=  __('City') ?>
                    </div>
                    <div class="wh-input">
                        <input type="text" class="required" title="<?=  __('City') ?>" name="city" placeholder="Fayetteville" id="wh-origin-city">
                    </div>
                </div>

                <div class="add-wh-input city-select" style="display:none;">
                        <div class="wh-input-label add-asterisk">
                        <?= /* @noEscape */ __('City') ?>
                        </div>
                        <div class="wh-input">
                            <select id="actname"></select>
                        </div>
                </div>

                <div class="add-wh-input">
                        <div class="wh-input-label add-asterisk">
                        <?= /* @noEscape */ __('State') ?>
                        </div>
                    <div class="wh-input">
                    <input type="text" class="required validate-alpha" title="<?= /* @noEscape */ __('State') ?>" maxlength="2" name="state" placeholder="GA" id="wh-origin-state">
                    </div>
                </div>

                <div class="add-wh-input">
                        <div class="wh-input-label add-asterisk">
                        <?= /* @noEscape */ __('Country') ?>
                        </div>
                        <div class="wh-input">
                            <input type="text" class="required  validate-alpha" title="<?= /* @noEscape */ __('Country') ?>" maxlength="2" name="country" placeholder="US" id="wh-origin-country">
                        </div>
                </div>

                <!--In store Pickup Section-->

                    <h3 class="wh-heading is-heading-left" id="wh-is-heading-left">
                        <?=
                        /* @noEscape */ __('In-store Pick Up')
                        ?>
                    </h3>
                    <?php if (!$advancedPlan): ?>
                        <a class="is-heading-right" href="https://eniture.com/magento2-worldwide-express-small-package/">
                            <?=
                            /* @noEscape */ __('Advanced Plan Required')
                            ?>
                        </a>
                    <?php endif; ?>
                <div class="message message-error error wh-instore-miles-postal-err">
                        <?=
                            /* @noEscape */ __('You must provide Miles or Postal Code.')
                        ?>
                </div>

                <div id="disableddiv" class="<?= $class ?>">
                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= /* @noEscape */ __('Enable In-Store Pick Up') ?>
                            </div>
                            <div class="wh-input">
                            <input type="checkbox" title="<?=  __('Enable In-Store Pick Up') ?>" name="instore-enable" id="enable-instore-pickup" <?= $disableInput ?>>
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?=  __('Offer if address is within (miles):') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?=  __('Offer if address is within (miles)') ?>" class="digits" maxlength="3" name="is-within-miles"  id="within-miles" <?= $disableInput ?> onpaste="return false">
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= __('Offer if postal code matches:') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?=  __('Offer is postal code matches') ?>"  name="is-postcode-match"  id="postcode-match" data-role="<?= $advancedPlan? 'tagsinput': ''; ?>" <?= $disableInput ?> >
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= __('Check Out Description:') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?=  __('Check Out Description') ?>" maxlength="25" name="is-checkout-descp" placeholder="In-store pick up" id="checkout-descp" <?= $disableInput ?>>
                            </div>
                    </div>
                </div>
                <!--In store Pickup Section End-->

                <!--Local Delivery Section-->

                <div class="row" style="clear: both">
                    <h3 class="wh-heading ld-heading-left" id="wh-ld-heading-left" >
                        <?= __('Local Delivery') ?>
                    </h3>
                    <?php if (!$advancedPlan): ?>
                        <a class="ld-heading-right" href="https://eniture.com/magento2-worldwide-express-small-package/">
                            <?=
                            /* @noEscape */ __('Advanced Plan Required')
                            ?>
                        </a>
                    <?php endif;?>
                </div>
                <div class="message message-error error wh-local-miles-postals-err">
                        <?= __('You must provide Miles or Postal Code.') ?>
                    </div>

                <!--Local Delivery Section Start-->
                <div id="disableddiv" class="<?= $class ?>">

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= __('Enable Local Delivery') ?>
                            </div>
                            <div class="wh-input">
                            <input type="checkbox" title="<?=  __('Enable Local Delivery') ?>" name="ld-enable" id="enable-local-delivery" <?= $disableInput ?>>
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= __('Offer if address is within (miles):') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?=  __('Offer if address is within (miles)') ?>" class="digits" maxlength="3" name="ld-within-miles" value=""  id="ld-within-miles" <?= $disableInput ?> onpaste="return false">
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= __('Offer if postal code matches:') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?=  __('Offer is postal code matches') ?>" data-role="<?= $advancedPlan? 'tagsinput': ''; ?>" name="ld-postcode-match"  id="ld-postcode-match" <?= $disableInput ?>>
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= __('Check Out Description:') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?=  __('Check Out Description') ?>" maxlength="25" name="ld-checkout-descp" placeholder="Local delivery" id="ld-checkout-descp" <?= $disableInput ?>>
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= __('Local Delivery Fee') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?=  __('Local Delivery Fee') ?>" class="number validate-wwesm-decimal-limit-2" maxlength="5" name="ld-fee"  id="ld-fee" <?= $disableInput ?> onpaste="return false">
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= __('Suppress other rates') ?>
                        <div class="suppressTooltip">[ ? ]
                                <span class="suppressTooltiptext"><?=  __("This setting only suppresses rates that would otherwise be returned by the Eniture Technology products.") ?></span>
                        </div>
                            </div>
                            <div class="wh-input">
                            <input type="checkbox" title="<?=  __('Suppress other rates') ?>" name="ld-sup-rates" id="ld-sup-rates" <?= $disableInput ?>>
                            </div>
                    </div>
                </div>
                <!--Local Delivery Section End-->
    </form>
</div>
