<section class="admin__page-section custom-tab-content">
    <h1>Additional Order Details</h1>
    <?php
    $order = $block->getOrder();
    $orderDetailData = $order->getData('order_detail_data');
    $orderDetailData = isset($orderDetailData) ? json_decode($orderDetailData, true) : null;
    if (!is_null($orderDetailData)) {
        $shimentNumber = 1;
        foreach ($orderDetailData['shipmentData'] as $key => $order) {
            $residential = $orderDetailData['residentialDelivery'];

            if (isset($order) && !empty($order)) {
                $code = (isset($order['quotes']['code'])) ? $order['quotes']['code'] : '';
                $title = (isset($order['quotes']['title']))?$order['quotes']['title'].' :':'';
                $rate = (isset($order['quotes']['rate'])) ? number_format((float)$order['quotes']['rate'], 2, '.', '') : '0.00';

                if ($shimentNumber > 1) {
                    ?>
                    <hr class="order-info-hr">
                    <?php
                }
                ?>

            <div class="order-detail-block">
                <h4 class='order-detail-hdng'>
                    Shipment <?= /* @noEscape */ $shimentNumber ?> > Origin & Services
                </h4>

                <div class="order-shipment-block">
                    <span class="list-item">
                        <?= /* @noEscape */ ucfirst($order['origin']['location']) .': '. /* @noEscape */ $order['origin']['senderCity'] .', '. /* @noEscape */ $order['origin']['senderState'] .' '. /* @noEscape */ $order['origin']['senderZip'] .'</span>' ?>
                        <span class="list-item">
                            <?= /* @noEscape */ $title .' $' . /* @noEscape */ $rate ?>
                        </span>
                    </span>
                </div>
                <?php
                $lineItems = $order['item'];
                $residential = ($residential)?'Residential Delivery':'';
                $findHazardous = array_column($lineItems, 'isHazmatLineItem');

                $hazordusFee = '';
                if (is_array($findHazardous) && count($findHazardous) > 0) {
                    foreach ($findHazardous as $hasStatus) {
                        if ($hasStatus == 'Y') {
                            $hazordusFee = 'Hazardous material';
                            break;
                        }
                    }
                }

                if (($code !== 'INSP' && $code !== 'LOCDEL') && ($residential || $hazordusFee)) {
                    ?>
                            <h4 class='order-detail-hdng'>Additional Information</h4>
                            <div class="order-additionalInfo-block">
                        <?php
                        if ($residential) {
                            ?>
                                    <span class="list-item">
                                <?= $residential ?>
                                    </span>
                            <?php
                        }
                        if ($hazordusFee) {
                            ?>
                                    <span class="list-item">
                                <?= $hazordusFee ?>
                                    </span>
                                    <?php
                        }
                        ?>
                            </div>
                    <?php
                }
                ?>
                <h4 class='order-detail-hdng'>
                    Shipment <?= /* @noEscape */ $shimentNumber ?> > items
                </h4>
                    <?php
                    foreach ($order['item'] as $key => $lineItem) {
                        ?>
                        <div class="order-item-block">
                            <span class="list-item">
                                <?= /* @noEscape */ $lineItem['piecesOfLineItem'] .' x '. /* @noEscape */ $lineItem['lineItemName'] ?>
                            </span>
                        </div>
                        <?php
                    }
                    ?>

            <!-- Clear the float effect -->
            <div class="en-clear"></div>
            </div>
                <?php
            }
            $shimentNumber++;
        }
    } else {
        ?>
        <h4>
            <?= /* @noEscape */ "No additional details are found!"; ?>
        </h4>
        <?php
    }
    ?>
</section>
